apiVersion: v1
kind: Secret
metadata:
  name: model-royale-secret
type: Opaque
stringData:
  ADMIN_PASSWORD: change-me
  SECRET_KEY: change-me-too
  POSTGRES_PASSWORD: change-me-db
  DATABASE_URL: postgresql+psycopg://royale:change-me-db@postgres:5432/royale
