apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "model-royale.webName" . }}
  labels:
    {{- include "model-royale.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      {{- include "model-royale.webSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "model-royale.webSelectorLabels" . | nindent 8 }}
      annotations:
        checksum/nginx: {{ include (print $.Template.BasePath "/nginx-configmap.yaml") . | sha256sum }}
        checksum/ui: {{ include (print $.Template.BasePath "/ui-configmap.yaml") . | sha256sum }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: web
          image: {{ include "model-royale.webImage" . }}
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: nginx
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
            - name: ui-config
              mountPath: /usr/share/nginx/html/config.json
              subPath: config.json
              readOnly: true
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
      volumes:
        - name: nginx
          configMap:
            name: {{ include "model-royale.fullname" . }}-nginx
        - name: ui-config
          configMap:
            name: {{ include "model-royale.fullname" . }}-ui
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "model-royale.webName" . }}
  labels:
    {{- include "model-royale.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.web.service.type }}
  selector:
    {{- include "model-royale.webSelectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: http
